name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.SCRIBD_SLACK_GENERIC_TOKEN }}
          channel: test-release-notification
  test-custom-message:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.SCRIBD_SLACK_GENERIC_TOKEN }}
          channel: test-release-notification
          message: <https://scribd.com|Custom message>
  test-overwrite-repository:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SCRIBD_GITHUB_GENERIC_TOKEN }}
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.SCRIBD_SLACK_GENERIC_TOKEN }}
          channel: test-release-notification
          repository: scribd/node-chassis
